const mockAPIResponse = {
  count: 20,
  next: 'https://swapi.dev/api/species/?search=n&page=2',
  previous: null,
  resource: 'species',
  results: [
    {
      average_height: '180',
      average_lifespan: '120',
      classification: 'mammal',
      created: '2014-12-10T13:52:11.567000Z',
      designation: 'sentient',
      edited: '2014-12-20T21:36:42.136000Z',
      eye_colors: 'brown, blue, green, hazel, grey, amber',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      hair_colors: 'blonde, brown, black, red',
      homeworld: 'https://swapi.dev/api/planets/9/',
      language: 'Galactic Basic',
      name: 'Human',
      people: [
        'https://swapi.dev/api/people/66/',
        'https://swapi.dev/api/people/67/',
        'https://swapi.dev/api/people/68/',
        'https://swapi.dev/api/people/74/',
      ],
      skin_colors: 'caucasian, black, asian, hispanic',
      url: 'https://swapi.dev/api/species/1/',
    },
    {
      average_height: '170',
      average_lifespan: 'unknown',
      classification: 'sentient',
      created: '2014-12-10T17:05:26.471000Z',
      designation: 'reptilian',
      edited: '2014-12-20T21:36:42.144000Z',
      eye_colors: 'black',
      films: ['https://swapi.dev/api/films/1/'],
      hair_colors: 'n/a',
      homeworld: 'https://swapi.dev/api/planets/23/',
      language: 'Galactic Basic',
      name: 'Rodian',
      people: ['https://swapi.dev/api/people/15/'],
      skin_colors: 'green, blue',
      url: 'https://swapi.dev/api/species/4/',
    },
    {
      average_height: '200',
      average_lifespan: 'unknown',
      classification: 'reptile',
      created: '2014-12-10T17:05:26.471000Z',
      designation: 'sentient',
      edited: '2014-12-20T21:36:42.144000Z',
      eye_colors: 'yellow, orange',
      films: ['https://swapi.dev/api/films/2/'],
      hair_colors: 'none',
      homeworld: 'https://swapi.dev/api/planets/29/',
      language: 'Dosh',
      name: 'Trandoshan',
      people: ['https://swapi.dev/api/people/24/'],
      skin_colors: 'brown, green',
      url: 'https://swapi.dev/api/species/7/',
    },
    {
      average_height: '160',
      average_lifespan: 'unknown',
      classification: 'reptile',
      created: '2014-12-10T17:05:26.471000Z',
      designation: 'sentient',
      edited: '2014-12-20T21:36:42.144000Z',
      eye_colors: 'yellow, orange',
      films: ['https://swapi.dev/api/films/2/'],
      hair_colors: 'none',
      homeworld: 'https://swapi.dev/api/planets/29/',
      language: 'Dosh',
      name: 'Trandoshan',
      people: ['https://swapi.dev/api/people/24/'],
      skin_colors: 'brown, green',
      url: 'https://swapi.dev/api/species/7/',
    },
    {
      average_height: '160',
      average_lifespan: 'unknown',
      classification: 'reptile',
      created: '2014-12-10T17:05:26.471000Z',
      designation: 'sentient',
      edited: '2014-12-20T21:36:42.144000Z',
      eye_colors: 'yellow, orange',
      films: ['https://swapi.dev/api/films/2/'],
      hair_colors: 'none',
      homeworld: 'https://swapi.dev/api/planets/29/',
      language: 'Dosh',
      name: 'Trandoshan',
      people: ['https://swapi.dev/api/people/24/'],
      skin_colors: 'brown, green',
      url: 'https://swapi.dev/api/species/7/',
    },
    {
      average_height: '160',
      average_lifespan: 'unknown',
      classification: 'reptile',
      created: '2014-12-10T17:05:26.471000Z',
      designation: 'sentient',
      edited: '2014-12-20T21:36:42.144000Z',
      eye_colors: 'yellow, orange',
      films: ['https://swapi.dev/api/films/2/'],
      hair_colors: 'none',
      homeworld: 'https://swapi.dev/api/planets/29/',
      language: 'Dosh',
      name: 'Trandoshan',
      people: ['https://swapi.dev/api/people/24/'],
      skin_colors: 'brown, green',
      url: 'https://swapi.dev/api/species/7/',
    },
    {
      average_height: '160',
      average_lifespan: 'unknown',
      classification: 'reptile',
      created: '2014-12-10T17:05:26.471000Z',
      designation: 'sentient',
      edited: '2014-12-20T21:36:42.144000Z',
      eye_colors: 'yellow, orange',
      films: ['https://swapi.dev/api/films/2/'],
      hair_colors: 'none',
      homeworld: 'https://swapi.dev/api/planets/29/',
      language: 'Dosh',
      name: 'Trandoshan',
      people: ['https://swapi.dev/api/people/24/'],
      skin_colors: 'brown, green',
      url: 'https://swapi.dev/api/species/7/',
    },
    {
      average_height: '160',
      average_lifespan: 'unknown',
      classification: 'reptile',
      created: '2014-12-10T17:05:26.471000Z',
      designation: 'sentient',
      edited: '2014-12-20T21:36:42.144000Z',
      eye_colors: 'yellow, orange',
      films: ['https://swapi.dev/api/films/2/'],
      hair_colors: 'none',
      homeworld: 'https://swapi.dev/api/planets/29/',
      language: 'Dosh',
      name: 'Trandoshan',
      people: ['https://swapi.dev/api/people/24/'],
      skin_colors: 'brown, green',
      url: 'https://swapi.dev/api/species/7/',
    },
    {
      average_height: '160',
      average_lifespan: 'unknown',
      classification: 'reptile',
      created: '2014-12-10T17:05:26.471000Z',
      designation: 'sentient',
      edited: '2014-12-20T21:36:42.144000Z',
      eye_colors: 'yellow, orange',
      films: ['https://swapi.dev/api/films/2/'],
      hair_colors: 'none',
      homeworld: 'https://swapi.dev/api/planets/29/',
      language: 'Dosh',
      name: 'Trandoshan',
      people: ['https://swapi.dev/api/people/24/'],
      skin_colors: 'brown, green',
      url: 'https://swapi.dev/api/species/7/',
    },
    {
      average_height: '160',
      average_lifespan: 'unknown',
      classification: 'reptile',
      created: '2014-12-10T17:05:26.471000Z',
      designation: 'sentient',
      edited: '2014-12-20T21:36:42.144000Z',
      eye_colors: 'yellow, orange',
      films: ['https://swapi.dev/api/films/2/'],
      hair_colors: 'none',
      homeworld: 'https://swapi.dev/api/planets/29/',
      language: 'Dosh',
      name: 'Trandoshan',
      people: ['https://swapi.dev/api/people/24/'],
      skin_colors: 'brown, green',
      url: 'https://swapi.dev/api/species/7/',
    },
  ],
};

const emptyResponse = {
  count: 0,
  next: 'https://swapi.dev/api/species/?search=n&page=2',
  previous: null,
  resource: 'species',
  results: [],
};

export { mockAPIResponse, emptyResponse };
